SELECT AREA_NAME 지역명, MEMBER_ID 아이디, MEMBER_NAME 이름, GRADE_NAME 등급명
FROM TB_MEMBER
JOIN TB_GRADE ON(GRADE = GRADE_CODE)
JOIN TB_AREA ON (AREA_CODE = AREA_CODE)
WHERE AREA_CODE = (
SELECT AREA_CODE FROM TB_MEMBER
WHERE 이름 = '김영희')
ORDER BY 이름 DESC;
	

-- AREA CODE 열 명시 부정확 -> USING 사용
-- SELECT 해석 순서 별칭 바꿈 -> 
-- 오름차순이니 DESC 아닌 ASC 사용
--

SELECT 
	AREA_NAME 지역명, 
	MEMBER_ID 아이디, 
	MEMBER_NAME 이름, 
	GRADE_NAME 등급명
FROM TB_MEMBER M
JOIN TB_GRADE ON (GRADE = GRADE_CODE)
JOIN TB_AREA A ON (A.AREA_CODE = M.AREA_CODE)
WHERE M.AREA_CODE = (
	SELECT AREA_CODE 
	FROM TB_MEMBER
	WHERE MEMBER_NAME = '김영희')		
ORDER BY 이름 ASC;





SELECT 
	AREA_NAME 지역명, 
	MEMBER_ID 아이디, 
	MEMBER_NAME 이름, 
	GRADE_NAME 등급명
FROM TB_MEMBER
JOIN TB_GRADE ON (GRADE = GRADE_CODE)
JOIN TB_AREA USING (AREA_CODE)
WHERE AREA_CODE = (
	SELECT AREA_CODE 
	FROM TB_MEMBER
	WHERE MEMBER_NAME = '김영희')		
ORDER BY 이름 ASC;