CREATE TABLE TB_TODO (
	TODO_TITLE     VARCHAR2(30) NOT NULL,
	TODO_DETAIL    VARCHAR2(1500), 
	TODO_COMPLETE  CHAR(1) DEFAULT 'X' CONSTRAINT COMPLETE_CHECK 
  CHECK (TODO_COMPLETE IN ('O', 'X')),
	REGDATE DATE DEFAULT CURRENT_DATE
);

COMMENT ON COLUMN TB_TODO.TODO_TITLE IS '할 일 제목';
COMMENT ON COLUMN TB_TODO.TODO_DETAIL IS '할 일 상세';
COMMENT ON COLUMN TB_TODO.TODO_COMPLETE IS '완료여부';
COMMENT ON COLUMN TB_TODO.REGDATE IS '작성 시간';


INSERT INTO TB_TODO 
VALUES ('JAVA', '공부', DEFAULT, DEFAULT);

INSERT INTO TB_TODO 
VALUES ('HTML', '공부', DEFAULT, DEFAULT);

INSERT INTO TB_TODO 
VALUES ('JS', '공부', DEFAULT, DEFAULT);

INSERT INTO TB_TODO 
VALUES ('JDBC', '공부', DEFAULT, DEFAULT);

SELECT *
FROM TB_TODO;

COMMIT;



SELECT 
	TODO_TITLE,
	TODO_DETAIL,
	TODO_COMPLETE,
	TO_CHAR(REGDATE, 'YYYY"년" MM"월" DD"일" AM HH24:MI:SS') REG_DATE 
FROM TB_TODO
ORDER BY REGDATE;



SELECT 
	ROW_NUMBER() OVER (ORDER BY REGDATE) AS TODO_NUMB,
	TODO_TITLE,
	TODO_DETAIL,
	TODO_COMPLETE,
	TO_CHAR(REGDATE, 'YYYY"년" MM"월" DD"일" AM HH24:MI:SS') REGDATE 
FROM TB_TODO;




SELECT 
	TODO_TITLE,
	TODO_DETAIL,
	TODO_COMPLETE,
	TO_CHAR(REGDATE, 'YYYY"년" MM"월" DD"일" AM HH24:MI:SS') REGDATE 
FROM (
	SELECT 
		ROW_NUMBER() OVER (ORDER BY REGDATE) AS TODO_NUMB,
		TODO_TITLE,
		TODO_DETAIL,
		TODO_COMPLETE,
		REGDATE
	FROM TB_TODO)
WHERE TODO_NUMB = 3;



UPDATE TB_TODO
SET
	TODO_COMPLETE = DECODE(TODO_COMPLETE, 'O', 'X', 'X', 'O')
WHERE 
	TODO_TITLE = 'JAVA'
	AND
	TODO_DETAIL = '공부';



SELECT *
FROM TB_TODO;

UPDATE TB_TODO
SET
	TODO_TITLE = 'AAA',
	TODO_DETAIL = 'BBB'
WHERE 
	TODO_TITLE = 'JAVA'
	AND
	TODO_DETAIL = '공부';


DELETE 
FROM TB_TODO
WHERE 
	TODO_TITLE = '11';

COMMIT;

